/** Generated by scripts/postbuild-workers.mjs — wrangler entry */
const WORKER_SITEMAPS = {
  '/sitemap.xml': `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://theislecheats.cc/</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/isle-cheats</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/features-list</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/hotkeys</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/complete-setup</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/disable-antivirus</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/undetected-status</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/reviews</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/faq</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/support</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/privacy</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/terms</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
</urlset>
`,
  '/google-sitemap.xml': `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://theislecheats.cc/</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/isle-cheats</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/features-list</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/hotkeys</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/complete-setup</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/disable-antivirus</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/undetected-status</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/reviews</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/faq</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/support</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/privacy</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/terms</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
</urlset>
`,
  '/sitemap-index.xml': `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://theislecheats.cc/sitemap-pages.xml</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://theislecheats.cc/sitemap-products.xml</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://theislecheats.cc/sitemap-forums.xml</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://theislecheats.cc/sitemap-forum-topics.xml</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </sitemap>
</sitemapindex>
`,
  '/sitemap-pages.xml': `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://theislecheats.cc/</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/reviews</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/faq</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/support</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/privacy</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/terms</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
</urlset>
`,
  '/sitemap-products.xml': `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://theislecheats.cc/isle-cheats</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
</urlset>
`,
  '/sitemap-forums.xml': `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://theislecheats.cc/forums</loc>
    <lastmod>2026-09-16T00:12:55Z</lastmod>
  </url>
</urlset>
`,
  '/sitemap-forum-topics.xml': `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://theislecheats.cc/forums/features-list</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/hotkeys</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/complete-setup</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/disable-antivirus</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
  <url>
    <loc>https://theislecheats.cc/forums/undetected-status</loc>
    <lastmod>2026-09-15T00:00:00Z</lastmod>
  </url>
</urlset>
`,
}

/**
 * HTTPS + sitemap XML for GSC (no www/apex host forcing).
 * Deploy entrypoint is worker.entry.mjs (generated in postbuild).
 */
import { adaptSitemapXmlForHost, robotsTxtForHost } from './lib/sitemap-host.mjs'

const XML_HEADERS = {
  'Content-Type': 'application/xml; charset=utf-8',
  'Cache-Control': 'public, max-age=0, must-revalidate',
  'X-Content-Type-Options': 'nosniff',
  'X-Sitemap-Source': 'worker',
}

function sitemapKey(pathname) {
  const normalized = pathname.replace(/\/+$/, '') || '/'
  return Object.keys(WORKER_SITEMAPS).find((key) => key.toLowerCase() === normalized.toLowerCase())
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url)

    if (url.protocol === 'http:') {
      url.protocol = 'https:'
      return Response.redirect(url.toString(), 301)
    }

    if (/\.xml\/+$/i.test(url.pathname)) {
      url.pathname = url.pathname.replace(/\/+$/, '')
      return Response.redirect(url.toString(), 301)
    }

    const path = url.pathname.replace(/\/+$/, '') || '/'
    if (path === '/robots.txt') {
      return new Response(robotsTxtForHost(url.hostname), {
        status: 200,
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'Cache-Control': 'public, max-age=3600',
        },
      })
    }

    const key = sitemapKey(url.pathname)
    if (key) {
      const xml = adaptSitemapXmlForHost(WORKER_SITEMAPS[key], url.hostname)
      return new Response(xml, { status: 200, headers: XML_HEADERS })
    }

    return env.ASSETS.fetch(request)
  },
}
