/**
 * Prepare dist/ for `wrangler deploy` (Workers static assets).
 * Keeps 301 rules from _redirects but drops Pages-only /* → 404.html (Workers uses wrangler not_found_handling).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const dist = join(root, 'dist')

function workersRedirectLine(raw) {
  const trimmed = raw.trim()
  if (!trimmed || trimmed.startsWith('#')) return null
  if (/\s404\s*$/i.test(trimmed) || /\/404\.html/i.test(trimmed)) return null
  if (/https?:\/\//i.test(trimmed)) return null

  const match = trimmed.match(/^(\S+)\s+(\S+)\s+(\d{3})$/)
  if (!match) {
    throw new Error(`Invalid _redirects line (Workers): ${trimmed}`)
  }
  const [, from, to, status] = match
  if (!from.startsWith('/')) {
    throw new Error(`_redirects source must be relative: ${from}`)
  }
  const dest = to.split('#')[0]
  if (!dest.startsWith('/') || /https?:\/\//i.test(dest)) {
    throw new Error(`_redirects destination must be relative: ${to}`)
  }
  return `${from} ${dest} ${status}`
}

const redirectsPath = join(dist, '_redirects')
if (existsSync(redirectsPath)) {
  const lines = readFileSync(redirectsPath, 'utf8').split(/\r?\n/)
  const kept = lines.map(workersRedirectLine).filter(Boolean)
  if (!kept.length) throw new Error('dist/_redirects has no Workers-compatible redirect rules')
  writeFileSync(redirectsPath, `${kept.join('\n')}\n`)
}

const sitemapFiles = [
  'sitemap.xml',
  'google-sitemap.xml',
  'sitemap-index.xml',
  'sitemap-pages.xml',
  'sitemap-products.xml',
  'sitemap-forums.xml',
  'sitemap-forum-topics.xml',
]

const workerSitemaps = {}
for (const name of sitemapFiles) {
  const path = join(dist, name)
  if (!existsSync(path)) throw new Error(`dist/${name} missing`)
  const xml = readFileSync(path, 'utf8')
  if (/<html|<!DOCTYPE/i.test(xml)) {
    throw new Error(`${name} is HTML, not XML`)
  }
  if (!xml.trimStart().startsWith('<?xml')) {
    throw new Error(`${name} must start with <?xml`)
  }
  workerSitemaps[`/${name}`] = xml
}

const robotsPath = join(dist, 'robots.txt')
if (!existsSync(robotsPath)) {
  throw new Error('dist/robots.txt missing')
}
const robots = readFileSync(robotsPath, 'utf8')
if (!robots.includes('Sitemap:') || !robots.includes('/sitemap.xml')) {
  throw new Error('robots.txt must reference sitemap.xml')
}
if (!robots.includes('https://theislecheats.cc/sitemap.xml')) {
  throw new Error('robots.txt Sitemap must use apex https://theislecheats.cc/sitemap.xml')
}

const indexXml = workerSitemaps['/sitemap-index.xml']
const childCount = (indexXml.match(/<sitemap>/g) || []).length
if (childCount !== 4) {
  throw new Error(`sitemap-index.xml must list 4 sitemaps, found ${childCount}`)
}
if (indexXml.includes('sitemap-images.xml')) {
  throw new Error('sitemap-index.xml must not reference removed sitemap-images.xml')
}

function escapeTemplate(value) {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

const entries = Object.entries(workerSitemaps)
  .map(([path, xml]) => `  '${path}': \`${escapeTemplate(xml)}\`,`)
  .join('\n')

writeFileSync(
  join(root, 'worker-sitemap-content.mjs'),
  `/** Generated by scripts/postbuild-workers.mjs — do not edit */\nexport const WORKER_SITEMAPS = {\n${entries}\n}\n`,
)

const workerSource = readFileSync(join(root, 'worker.mjs'), 'utf8')
const workerBody = workerSource.replace(
  /^import\s+\{ WORKER_SITEMAPS \} from '\.\/worker-sitemap-content\.mjs'\s*\r?\n/m,
  '',
)
const bundled = `/** Generated by scripts/postbuild-workers.mjs — wrangler entry */\nconst WORKER_SITEMAPS = {\n${entries}\n}\n\n${workerBody}`
const entryPath = join(root, 'worker.entry.mjs')
writeFileSync(entryPath, bundled)
if (bundled.length < 6000) {
  throw new Error('worker.entry.mjs too small — sitemap XML may be missing from deploy bundle')
}

writeFileSync(
  join(dist, 'robots.txt'),
  `User-agent: *
Allow: /

Sitemap: https://theislecheats.cc/sitemap.xml
`,
)

console.log('Workers deploy prep OK')
