/** First-party assets generated by scripts/generate-seo-assets.mjs. */
import { ISLE_ESP_FOREST, ISLE_ESP_RIVER } from './media'

export const ISLE_OG = '/og/default.jpg'
export const ISLE_HERO = '/media/product-hero.webp'
export const ISLE_COVER = '/media/product-cover.webp'

export type ImageSeoFields = {
  alt: string
  title: string
  caption: string
}

export const IMAGE_SEO: Record<
  string,
  ImageSeoFields & {
    heroAlt: string
    heroTitle: string
    heroCaption: string
  }
> = {
  isle: {
    alt: 'Evrima ESP and radar product artwork',
    title: 'Evrima ESP Product Details',
    caption: 'Product details for Evrima ESP, radar, stream-proof mode and HWID spoofer support',
    heroAlt: 'Evrima ESP features, compatibility, price and checkout',
    heroTitle: 'Evrima ESP Features and Checkout',
    heroCaption: 'Review supported Evrima features and current status before checkout',
  },
}

type PageImage = ImageSeoFields & { src: string }

const SOCIAL_IMAGE: PageImage = {
  src: ISLE_OG,
  alt: 'The Isle Cheats for Evrima',
  title: 'The Isle Cheats',
  caption: 'Live status, features, price and checkout for The Isle Evrima',
}

export const PAGE_IMAGES: Record<
  'home' | 'forums' | 'reviews' | 'faq' | 'support' | 'product',
  PageImage
> = {
  home: {
    src: ISLE_ESP_FOREST,
    alt: 'The Isle Cheats Entity ESP gameplay on Evrima',
    title: 'The Isle Cheats ESP Gameplay',
    caption: 'Entity ESP gameplay shown before checkout.',
  },
  forums: {
    src: ISLE_ESP_RIVER,
    alt: 'The Isle Cheats forum gameplay reference',
    title: 'The Isle Cheats Forum Gameplay',
    caption: 'Evrima ESP reference for setup and feature threads.',
  },
  reviews: {
    src: ISLE_ESP_FOREST,
    alt: 'The Isle Cheats gameplay accompanying verified reviews',
    title: 'The Isle Cheats Review Gameplay',
    caption: 'Evrima gameplay accompanying verified buyer feedback.',
  },
  faq: {
    src: ISLE_ESP_RIVER,
    alt: 'Evrima ESP gameplay accompanying pre-purchase answers',
    title: 'Evrima ESP FAQ Gameplay',
    caption: 'Visible product screenshot accompanying purchase questions.',
  },
  support: {
    src: ISLE_ESP_FOREST,
    alt: 'The Isle Cheats support gameplay reference for load and inject help',
    title: 'The Isle Cheats Support Gameplay',
    caption: 'Evrima ESP reference accompanying post-purchase support and inject help.',
  },
  product: {
    src: ISLE_ESP_RIVER,
    alt: 'Evrima ESP product gameplay beside a river',
    title: 'Evrima ESP Product Gameplay',
    caption: 'Visible ESP gameplay accompanying product features and checkout.',
  },
}

export function getGameImage(_slug: string): string {
  return ISLE_COVER
}

export function getProductHeroImage(slug: string): string {
  return slug === 'isle' ? ISLE_HERO : getGameImage(slug)
}

export function getOgImage(path?: string): string {
  if (!path || path === '/') return PAGE_IMAGES.home.src
  if (path === '/isle-cheats') return PAGE_IMAGES.product.src
  if (path === '/forums') return PAGE_IMAGES.forums.src
  if (path === '/reviews') return PAGE_IMAGES.reviews.src
  if (path === '/faq') return PAGE_IMAGES.faq.src
  if (path === '/support') return PAGE_IMAGES.support.src
  if (path === '/privacy' || path === '/terms') return PAGE_IMAGES.faq.src
  return ISLE_OG
}

export function getPageImage(key: keyof typeof PAGE_IMAGES) {
  return PAGE_IMAGES[key]
}

export function getImageAlt(
  slug: string,
  name: string,
  variant: 'catalog' | 'product' = 'catalog',
): string {
  const seo = IMAGE_SEO[slug]
  if (seo) return variant === 'product' ? seo.heroAlt : seo.alt
  return variant === 'product' ? `${name} product details` : `${name} product artwork`
}

export function getImageTitle(
  slug: string,
  name: string,
  variant: 'catalog' | 'product' = 'catalog',
): string {
  const seo = IMAGE_SEO[slug]
  if (seo) return variant === 'product' ? seo.heroTitle : seo.title
  return `${name} product`
}
